name: Run marcar.py on Weekdays

# Define o horário de execução do job
on:
  schedule:
    - cron: '0 8 * * 1-5'   # Executa às 08:00 (UTC) de segunda a sexta-feira
    - cron: '0 17 * * 1-5'  # Executa às 17:00 (UTC) de segunda a sexta-feira
    
  workflow_dispatch:

jobs:
  run-job:
    runs-on: ubuntu-latest  # Usa uma máquina Ubuntu para rodar o job

    steps:
    # Passo 1: Faz o checkout do código do repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Passo 2: Instala o Python e as dependências
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Define a versão do Python

    # Passo 3: Instala as dependências do requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Passo 4: Executa o script marcar.py
    - name: Run marcar.py
      run: python marcar.py
